# # # # # # # # # # # # # # # # # # # # # # 
#           Made by Wazup92               #
#     If you really like the plugin       #
#     Then please dont forget to leave    #
#        A positive 5 stars review!       #
# # # # # # # # # # # # # # # # # # # # # # 
# 
# Rollback speed is measured in Blocks per tick, default settings are made for average servers
# Queue-Size is how many arenas can rollback in the same time, Send-Status-Update-Every is how often the rollback percentage updates, and its in ticks
# The Max-Arena-Size is completely up to you, thats why i added it here, but obviously, the smaller the size is, the better.
# Executed commands on Player-Win variables -> %player%, %world%, Arena-Start -> %world%
# Custom slots format -> 'Slot amount : Permission'
# Mystery-Box chances don't have to add up to 100%
# If Empty-Chunk-Generator is enabled, the world importing feature will import worlds with a custom generator that generates empty chunks
# Please BE AWARE. Holographic-Stats are resource intensive. and so is an animated Title
# Chest-Checks -> Slot-Overwrite is the amount of times the plugin tries to find a random slot that is empty before it just overwrites an occupied one [Ranges from 1, 10]
# Chest-Checks -> Item-Duplicate is the amount of times the plugin tries to generate a random item that is not inside the chest before it just places anything. [Ranges from 1, 10]
# Increasing Chest-Checks too much might decrease the performance.

Load-Delay-Ticks: 10
Empty-Chunk-Generator: false
use-UUID: false
use-Vault: false
String-Coins: 500
Coins-Per-Kill: 10
Coins-Per-Win: 100
Min-Exp-Per-Kill: 2
Max-Exp-Per-Kill: 5
Celebration-Length: 5
Block-Behind-Signs: 159
Max-Warnings: 3
Party-Invitation-Length: 30
Lobby-Chat: false
In-Game-Chat: false
Spectators-Chat: false
Lobby-Scoreboard-Enabled: true
Allow-Spectators-Inventory-View: true
Load-Skins-On-Skulls: true
Disable-Natural-Mob-Spawning: true
Show-Health-On-Bow-Hit: true
Fireworks-Enabled: true
Allow-Spectator-Join: true
Leash-Mobs: false
Void-Instant-Kill: true
Teleport-Mobs: true
Display-Rank-In-Chat: false
Selling-Value: 0.5
Max-Arena-Size: 4500000
Leave-Countdown-Seconds: 5
Update-Leaderboard-Every-Minutes: 10
Broadcaster-Send-Every: 60
Check-For-Updates: false
Broadcast-Time:
- 60
- 30
- 15
- 5
- 4
- 3
- 2
- 1
Allowed-Commands:
- sw
- r
- msg
- ban
- kick
- report
- zglos
- helpop
- warn
Mystery-Box:
  Block-Type: ENDER_CHEST
  Cost: 500
  Contents:
  - 'Kits : 30%'
  - 'Cages : 35%'
  - 'Trails : 35%'
  Rarities:
  - 'Common : 60%'
  - 'Rare : 30%'
  - 'Legendary : 10%'
Party:
  Default-Slots: 6
  Custom-Slots:
  - '9 : skywars.party.slots.4'
  - '10 : skywars.party.slots.5'
  - '11 : skywars.party.slots.6'
Hotbar-Items:
  Arena-Selector:
    enabled: true
    slot: 1
  Shop:
    enabled: true
    slot: 7
  Party:
    enabled: true
    slot: 8
  Profile:
    enabled: true
    slot: 2
  Vote:
    enabled: true
    slot: 1
  Inventory:
    enabled: true
    slot: 2
  Quit:
    enabled: true
    slot: 9
Chest-Checks:
  Slot-Overwrite: 3
  Item-Duplicate: 3
Bungee-Mode:
  enabled: false
  hub: lobby
  restart-command: restart
MySQL:
  enabled: false
  table: Skywars
  host: localhost
  port: 3306
  database: database
  username: root
  password: root
  max_uuid_size: 36
Rollback:
  Scan-Speed: 50000
  Repair-Speed: 1000
  Queue-Size: 1
  Send-Status-Update-Every: 20
Ranks:
  First-Rank-Exp: 20
  Rank-Modifier: 1.3
  Max-Rank: 30
  Commands: []
Executed-Commands:
  Player-Win:
  - alert skywars &8[&6Skywars&8] &7Gracz &e%player% wygral gre na arenie &e%area%&7!
  Arena-Countdown:
  - alert skywars &8[&6Skywars&8] &7Arena &e%arena% &7rozpoczyna sie za &e%seconds% &7sekund!
  Arena-Start: []
Killstreaks: []
Saving-Task:
  Enabled: true
  Save-Every-Minutes: 10
Winners-Map:
  enabled: false
  display-image: false
  image-url: http://i.imgur.com/FrgIjmJ.png
Team-Coloring:
  default: '&a'
  randomizer-enabled: true
  randomizer-colors:
  - '&2'
  - '&3'
  - '&5'
  - '&6'
  - '&7'
  - '&8'
  - '&9'
  - '&a'
  - '&b'
  - '&c'
  - '&d'
  - '&e'
Scoreboard-Title-Animation:
  enabled: true
  interval: 8
  frames:
  - '&6&lSKYWARS'
  - '&e&lSKYWARS'
  - '&6&lSKYWARS'
  - '&e&lSKYWARS'
  - '&6&lSKYWARS'
  - '&c&lSKYWARS'
  - '&e&lS&6&lKYWARS'
  - '&6&lS&e&lK&6&lYWARS'
  - '&6&lSK&e&lY&6&lWARS'
  - '&6&lSKY&e&lW&6&lARS'
  - '&6&lSKYW&e&lA&6&lRS'
  - '&6&lSKYWA&e&lR&6&lS'
  - '&6&lSKYWAR&e&lS'
Action-Bar-Enabled: true
Titles:
  enabled: true
  fadeIn: 10
  stay: 40
  fadeOut: 10
Lobby: skywars, 1.5, 91, -1.5, -358.75565, 0.0068776966
